name: Character Customization Build
on: [push]
jobs:
 build:
  runs-on: windows-latest
  steps:
  - name: Checkout code
    uses: actions/checkout
  - name: Add MSBuild to PATH
    uses: microsoft/setup-msbuild
  - name: Run MSBuild
    run: msbuild.exe .\Customization\Customization.proj
  #- name: Setup VSTest path
  #  uses: darenm/Setup-VSTest@v1
  #- name: Run VSTest
  #  run: vstest.console.exe /Platform:x64 .\path\to\dll
