name: Character Customization Build
on: [push]
jobs:
 build:
  runs-on: windows-latest
  steps:
  - name: Checkout code
    uses: actions/checkout@v2
    id: checkout_code
  - name: Setup MSBuild and add to PATH
    uses: microsoft/setup-msbuild@v1.0.0
    id: setup_msbuild
    env:
     ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
  - name: Run MSBuild
    id: run_msbuild
    working-directory: $
    run: msbuild .\Customization.sln
    env:
     ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
